### ISSUE TITLE
Alert us via email or chat when there is any issue in the cluster

### ISSUE THREAD

**Issue by w-le** [place-labs/k8s-helm#62]
Suggested ideas (open to others):
- Notify us via the google chat channel "stderr" when:
  - Any pods in the namespace 'placeos' end with a non 0 exit code
  - Any pods in the namespace 'placeos' are rescheduled on to a different node
  - Any pods in the namespace 'placeos' get high cpu or ram pressure (e.g. 95%?)
  - Any nodes hit cpu or ram pressure (e.g. 95%?)

**Comment by w-le** [comment]
hey @jeremyw24 perhaps we can get Ali to work on this?

**Comment by naqvis** [comment]
@w-le  Hi Will, can you please elaborate more?  From the title doesn't know if things need to be looked at infra level or app level.

**Comment by w-le** [comment]
yep done, open to other suggestions for alerts. 
Do you have any @viv-4 ?
